---
title: "Il faut que tout bouge pour que rien ne change"
subtitle: "Forum de l'AAF"
author: "Anne-Laure Donzel & Julien Benedetti"
date: "26 mars 2025"
toc: true
editor: visual
---

# Support de l'intervention

Téléchargez le support [ici](AAF2025_Donzel_Benedetti.pdf).

# Texte de l'intervention

Vous pouvez retrouver toutes les références bibliographiques citées [ici](biblio.qmd).

## Introduction

Nous avons choisi de proposer une intervention qui s'intitule "Archives et infrastructures, il faut que tout bouge pour que rien ne change". Derrière ce titre énigmatique, nous souhaitons aborder le sujet des archives avec un regard issu des recherches en Science & Technology Studies et, en particulier, en s'inspirant des travaux sur les infrastructures.

En entendant le terme archives, vous avez sans aucun doute, différentes images qui vous viennent en tête : votre dernière collecte, un classement, une communication en salle de lecture… Les images qui vous viennent à l'esprit, à l'évocation de la notion d'infrastructure, sont peut-être moins nettes. Mais vous devez finir par imaginer une route, un réseau ferré, un barrage etc.

Vous devez donc difficilement faire le lien entre ces deux notions. Pour cela, nous devons élargir notre vision de l'infrastructure. Pour Susan Leigh Star l'infrastructure est par définition invisible, *\[elle\] constitue une partie de l'arrière-plan d'autres types d'activités*. Elle est prête à l'emploi. Et elle est également un concept fondamentalement relationnel.

Les STS, particulièrement dans la pratique anglo-saxonne, identifient un type d'infrastructure particulière, l'infrastructure de la connaissance (*knowledge infrastructure*). Le chercheur américain Paul N. Edwards la définie comme un *réseau solide de personnes, d'objets et d'institutions qui génèrent, partagent et maintiennent/conservent des connaissances spécifiques sur les mondes humain et naturel* (*robust network of people, artifacts, and institutions that generate, share, and maintain specific knowledge about the human, and natural worlds*).

Sur la base de ces définitions, nous allons considérer les archives et en particulier les archives numériques, comme une infrastructure de la connaissance. Et la définition d'Edwards fait apparaître une notion que nous allons développer durant cette intervention : la maintenance.

Dans leur ouvrage *Le soin des choses*, Jérôme Denis et David Pointille, définissent la maintenance comme l'art de faire durer les choses. Vous devez commencer à voir les liens se tisser entre archives, infrastructure et maintenance. L'acte d'archiver vise à la conservation durant un temps long des documents et des données. Archiver, c'est un acte qui intègre des formes de maintenance, rarement envisagée comme telle, sur lesquelles nous allons revenir.

Nous verrons donc, dans un premier temps, comment le concept d'infrastructure s'applique aux archives. Ensuite, nous nous pencherons sur les archives numériques comme infrastructure et enfin, nous explorerons quelques exemples dans lesquels l'infrastructure est devenue visible pour les archivistes numériques.

## Partie 1 - Penser les archives comme une infrastructure

Pour commencer, je vous propose de revenir sur quelques définitions et de voir, plus précisément, les liens entre archives et infrastructure.

### Slide 1-1 - Sur la notion d'infrastructure

Le terme “infrastructure” est né au XIXè s. en France avec le développement de l’ingénierie. Le terme était utilisé pour distinguer tout ce qui venait en amont ou à côté de la construction pure (les études, plans, travaux préalables…). Cette dernière constitue, de son côté, la superstructure (les rails par ex. dans le cadre du réseau ferré). Alors qu’elle a inventé le terme, la France a du mal à sortir ce concept de l’ingénierie pour en faire une notion adaptée dans d’autres contextes, en particulier pour les SHS. Ce qui n’est pas le cas dans la pratique archivistique anglo-saxonne qui conçoit, depuis longtemps, les [archives comme une infrastructure](https://www.ideals.illinois.edu/items/199) ou comme une partie d’une infrastructure plus vaste : infrastructure de la connaissance (Knowledge infrastructure) ou infrastructure scientifique (scholarly infrastructure).

La notion d’infrastructure offre différents avantages : comme nous l’avons vu avec la définition de Paul Edwards en introduction, elle permet de relier l’ensemble des éléments qui composent un objet complexe. Une infrastructure, c’est un réseau de personnes, d’artefact et d’institutions. Elle est relationnelle : par des échanges, des flux, des transferts entre différentes parties prenantes, personnes physiques ou morales. 

### Slide 1-2 - Archives et infrastructures dans la pratique archivistique française

Nous pouvons démarrer par un premier constat : la notion d'infrastructure est très peu utilisée dans la théorie archivistique française.

En regardant les rapports annuels du SIAF entre 2000 et 2023, nous voyons la notion d’infrastructure n’apparaître que 13 fois. Et quasi exclusivement en lien avec l’archivage numérique, sur des aspects d’architecture technique, ou comme synonyme de “système d’information”. Pourtant, la notion d’infrastructure nous semble parfaitement adaptée pour les archives et, en particulier, pour les archives numériques. Par la variété de leurs missions, les services d’archives constituent une infrastructure. Comme le souligne Ciaran B. Trace, l’infrastructure des archives est à la fois intellectuelle, physique et informationnelle.

-   Intellectuelle : les archivistes ont théorisé leur discipline, ont conceptualisé leurs pratiques. Cela passe par la création de définitions, de normes et d’un cadre théorique sur les archives.

-   Physique : la conservation des archives reposent sur le stockage, la gestion d’espaces, la gestion de crise... La matérialité des artefacts conservés entre également en ligne de compte, bien évidemment.

-   Informationnelle : l’objectif est de pouvoir fournir, in fine, de l’information, là aussi en mettant en place un environnement spécifique qui permet de prendre en charge une grande variété de sources et de répondre à la diversité des objets de recherches (administratives, scientifiques, personnelles…).

L'infrastructure est donc un concept qui s'applique parfaitement aux archives. Avant de poursuivre, revenons sur deux caractéristiques importantes de l'infrastructure et qui sont indispensables pour notre exploration des liens entre archives, infrastructure et maintenance.

### Slide 1-3 - Ce qui caractérise les infrastructures

Les infrastructures possèdent 2 caractéristiques principales : elles doivent être durables (elles sont pensées pour le long terme, comme nous l'avons vu avec la citation de Timothy Mitchell) et elles sont intrinsèquement fragiles. Les deux caractéristiques étant en partie liées.

Durabilité des infrastructures : la durabilité c’est la capacité à demeurer stable dans le temps. L’infrastructure doit pouvoir continuer de servir ses objectifs durant une longue (voir une très longue) période. Vous percevez sans doute bien sur cet aspect en quoi les archives constituent une infrastructure.

Fragilité des infrastructures : cette deuxième caractéristique peut sembler, a priori, une faiblesse. C’est souvent un biais de nos sociétés : être fragile est un défaut. Ce n’est pas cependant pas le cas. La reconnaissance de la fragilité des infrastructures permet d’intégrer très tôt le besoin de maintenance et du soin nécessaire à leur maintien dans le temps. Il faut accepter la défaillance, le risque de perte pour mettre en place tous les mécanismes de lutte contre cette dégénérescence. Et, il faut réaliser la maintenance et le soin des éléments en eux-mêmes (les objets archivés), mais aussi de l’ensemble des éléments “autour” de ces objets.

Nous avons pour le moment fait peu de lien direct avec le cœur de notre sujet qui porte sur les archives numériques. Nous allons désormais voir, concrètement, comment l’infrastructure se matérialise dans les archives numériques.

## Partie 2 - L'archive dans l'infrastructure numérique

Les archivistes sont depuis plusieurs décennies dans une adaptation professionnelle, à la fois en raison de la transformation de la production d'archives, mais aussi dans leur production de données archivistiques et d'artefact de consultation et diffusion. Dans cette partie, je vous propose d'explorer ce que le numérique fait à l'archive infrastructure.

### Slide 2-1 - L'archiviste à travers les méthodes de conservation préventive ou curative est dans une relation de soin aux archives, dans le but de "faire durer".
 
Dorénavant, l'archiviste intervient directement "sur" le document, y compris en partie sur son contenu. Ceci se caractérise dans des séquences de transformation de l'objet binaire, cela est le cas dans les étapes de migrations de formats ou de compression de fichier. Différentes théories existent sur la place et le rôle de l'archiviste : gardien ou acteur, conservateur ou performeur. Ciaran B. Trace pose la question de l'agentitivité de l'archiviste, quelle place pour l'archiviste dans la maintenance de l'infrastructureinformationnelle ? Nous pouvons faire ici un parallèle avec la place du chargé de maintenance tel que décrit par Jérôme Denis. Il est à la fois dans l'intervention, mais devient invisible d'un point de vue extérieur.
	 
Pour autant, l'intervention des archivistes, à force d'être naturalisée et non remise en question, peut aboutir à l'inverse de l'effet attendu. Citons ainsi [Bertrand Caron](https://digipres.fr/archives/90), conservateur à la BnF en charge de la préservation numérique :

> foutez la paix aux fichiers. Pourquoi cette injonction ? Parce que, dans la vulgate préservationniste, largement fondée sur des idées préconçues et élaborée dans les années 2000, l’interventionnisme était de mise, et nous a sans doute amenés à faire des bêtises.
	 
Il défend ici l'idée qu'à vouloir uniformiser les contenus, on contrevient à leur lisibilité dans le temps et surtout à un risque de disparition du contexte de production, via un effacement des métadonnées. On voit ici que le numérique provoque un changement de rapport à l'objet "archive". L'archiviste par ses gestes d'archivation ajoutent des métadonnées (enrichissement) mais aussi sur Celles-ci (changement de standard).
	 
Ainsi, pour dénaturaliser les actions des archivistes, il faut aller vers une valorisation de la technicité archivistique et s'intéresser aux différentes couches des objets binaires. Il faut prendre garde à ce que ce sujet ne soit pas l'apanage d'un ou deux experts dans un service, comme c'est décrit dans le Rapport ["Une réforme numérique ? Les mutations du travail archivistique dans les services d’archives départementales"](https://francearchives.gouv.fr/fr/article/689545291) (2024).

Ainsi, le philosophe Marcello Vitali-Rosati propose une inversion de perspective et pousse à une économie de moyen :

> Choisir le _low tech_ n'est pas la solution de quelqu'un qui ne serait pas assez compétent pour utiliser une technologie plus avancée, mais au contraire le choix d'une personne très compétente. Le _low tech_, comme le souligne Gauthier Roussilhe, demande un haut degré de compétences techniques de la part des personnes qui l'adoptent. A partir de cette idée, Roussilhe propose une sorte d'équation : plus de "haute technologie" implique moins de compétences techniques et _vice versa_. (_Éloge du bug_)

Le numérique est formé d'une importante intrication technique (format, support, réseau, stockage), d'où l'importance de "mettre les mains" dans la technique.

### Slide 2-2 - L'archivage est télescopé par un changement dans l'infrastructure technique

Si pendant longtemps les fonds d'archives, et les archivistes étaient rassemblés dans une unité de lieu - "les Archives" - le numérique bouscule ce fait. En effet, le stockage des documents et données numériques, que cela soit par leur localisation ou les choix techniques réalisés, échappent aux archivistes. Les infrastructures numériques sont alors prises en charge par les directions de l'informatique ou même de plus en plus souvent par des prestataires. Le stockage numérique, des archives nativement numériques comme des copies patrimoniales, est pris dans l'infrastructure globale de l'organisation, pour autant l'archiviste doit savoir être prescripteur. Là aussi, l'archiviste a une expertise à faire valoir, ne citons que comme exemple les exigences d'hébergement sur 2 sites distants prévus par les normes d'archives électroniques, ou l'utilisation d'offre froide.
    
> The cloud does not exist in a vacuum. It is dependent on a far-reaching fabric of interactions, telecoms, internet service providers, and hardware manufacturers, all of which are motivated by timescales far removed from a century. (Maxwell Neely-Cohen)

On voit donc que l'un des principaux changements est lié à un rapport à l'espace, mais aussi à l'unicité de l'archive. L'archiviste est dans un domaine partagé dont il n'est plus le seul dépositaire. Le numérique créé des dépendances (éditeur, technicien tiers, fabricant de support), ceci fait apparaître plus tôt les failles de maintenance, révélant ainsi l'infrastructure.

### Slide 2-3 - Décentralisation des acteurs : mise à mal de la position de gatekeeper

Pour celles et ceux préférant le grec à l'anglais, nous pourrions aussi nous référer à l'[archonte](https://www.idixa.net/Pixa/pagixa-1106211048.html), dont le rôle de gardien est décrit par Jacques Derrida dans _Le mal d'archives_. Comme nous l'avons déjà énoncé, l'infrastructure et sa maintenance s'envisagent aussi par le prisme de l'organisation sociale. Le numérique a accéléré certaines pratiques, modifiant ainsi le rapport à l'archives.

Les pratiques communautaires de l'archivage se développent plus facilement aujourd'hui via le médium numérique. Comment le service d'archives s'intègrent dans ces espaces ? Peut-il s'intégrer dans différentes infrastructures informationnelles ? Star & Bowker analyse ainsi cet aspect d'entremêlement :

> Toute infrastructure opérationnelle sert simultanément plusieurs communautés de pratique, qu'elle appartiennent à une seule organisation ou qu'elles soient réparties entre plusieurs organisations. Un système d'information hospitalier, par exemple, doit répondre aux agendas conjoints et séparés des infirmières, des archivistes, des agences gouvernementales, des médecins, des épidémiologistes des patients, et ainsi de suite. Pour ce faire, il doit mettre en jeu des régimes stables d'objets-frontière de sorte que toute communauté de pratique puisse communiquer avec le système d'information et en tirer les types d'objets informationnels dont elle a besoin. (Star & Bowker p. 387)

On voit ici poindre ce qui pourrait être une redéfinition du rôle de l'archiviste, plus dans un rôle de passeur, de médiateur, apportant des garanties ou une expertise permettant à l'autre de se saisir des archives, voire d'en être les conservateurs. La notion de soin, de maintenance serait à éclairer par les travaux archivistiques sur le post-custodial.

> concerne les situations dans lesquelles les créateurs de documents continuent à conserver les documents d'archives, les archivistes assurant la supervision de la gestion, même s'ils peuvent également avoir la garde d'autres documents. (traduction de la [définition](https://dictionary.archivists.org/entry/postcustodial.html) de la SAA).

Nous allons donc voir dans notre dernière partie à travers plusieurs exemples comment l'infrastructure, quand elle n'est pas l'objet de soin, casse.

## Partie 3 - Quand l'infrastructure devient visible

Dans cette dernière partie nous voulons insister sur l'importance du "prêter attention à". Il s'agit d'une prise de conscience et d'une reconnaissance de la fragilité des archives dans une dimension multiple. À travers quatre exemples nous abordons la fragilité juridique, puis organisationnelle, technique et enfin politique.

### Slide 3-1 - Exemple du cas Australien

Depuis plus de quinze ans, Tim Sherratt propose des outils numériques pour permettre des recherches en histoire, notamment. Ces outils sont dépendants d'API des Archives nationales d'Australie. Récemment, Sherratt a vu ses clefs d'API [révoquées](https://updates.timsherratt.org/2025/02/24/years-of-work-on-trove.html), faisant ainsi tomber les services et les usages des scientifiques. Cette révocation n'a fait l'objet aucune communication préalable du service d'archives, alors pourquoi ce changement ? 

Les AN d'Australie ont modifié leurs conditions d'utilisation, et interdisent dorénavant la réutilisation des fichiers d'archives numérisés, seuls les métadonnées sont exploitables. Mais Sherratt fait justement remarqué qu'il n'a aucunement contourné le système technique, puis les API proposent des flux d'informations comprenant les documents. On voit ici apparaître la fragilité d'une infrastructure numérique, non d'un point de vue technique (les API sont toujours fonctionnelles) mais pour des modifications légales. Les AN d'Australie par ce choix unilatéral et sans prise en compte des usages existants met aussi en lumière l'absence d'échanges et de dialogues entre acteurs d'une même infrastructure.

### Slide 3-2 - Exemple de Sherpa

Évoquons maintenant un projet, disparu, concernant l'archivage numérique. Le SIAF, afin de faciliter l’essor de l'archive numérique, a soutenu des développements d'outils informatiques. C'est le cas notamment pour les éditeurs de profil d'archivage en langage XML SEDA. Nous en sommes actuellement au troisième outil. Le deuxième nous intéresse particulièrement. La SIAF a commandé un outil disponible en mode web et appelé SHERPA. 

L'objectif de cette plateforme était de fournir un outil de production pour les archivistes mais surtout une mise en commun des profils pour constituer une sorte de bibliothèque de référence. Hélas, le projet a fait long feu et n'est plus accessible. Il a une vie spectrale à travers quelques liens que l'on trouve sur le web. Que cela soit dans une [formation](https://www.formation-serda.com/formations-archives/utilisation-du-seda-de-la-redaction-dun-profil-la-constitution-dun-paquet) de la SERDA ou la [documentation](https://www.programmevitam.fr/vitam-doc/fr/master_7.1.x/sections/Vademecum_pa.html) de Vitam. 

En consultant la version archivée par [Internet Archives](https://web.archive.org/web/20190307022631/https://francearchives.fr/sherpa/authorityrecord) on comprend pourquoi ce projet n'a pas réussi, en effet aucune organisation de modération ou validation des profils n'avaient été envisagées. Cela a abouti à la création en grand nombre de profils "brouillon", rendant invisible des profils pouvant servir de référence. On voit ici que l'outil technique n'est pas à remettre en cause, la faiblesse du projet a tenu à une absence de prise en compte d'une infrastructure sociale et organisationnelle.

### Slide 3-3 - Exemple de la base Léonore

Plus près de nous la refonte de la [base Léonore](https://www.leonore.archives-nationales.culture.gouv.fr/ui/) a aussi été un moment de mise en lumière de l'infrastructure documentaire et de l'ensemble des interstices dans lesquelles elle se niche. La base Léonore expose les données des récipiendaires de la Légion d'honneur, et elle a connu une importante refonte en 2021.

Si celle-ci a apporté d'importantes évolutions techniques, elle n'a pas forcément fait l'unanimité et a eu un impact négatif sur des infrastructures liées à Léonore, comme Wikipedia et Wikidata. En effet, Léonore est une source d'information biographique et elle était utilisée dans de nombreuses fiches du projet encyclopédique. Le lien se faisait à partir des identifiants attribués à chaque légionnaire. Lors de la refonte ces identifiants n'ont pas été repris et de nouveaux, correspondant à la nouvelle base de données, ont été créés. Ceci a entraîné en cascade des milliers de liens morts, et un besoin de "réparation" par les wikimédiens. Comme dans l'exemple précédent, les usages externes n'ont pas été évalués lors du changement de l'outil. Dans ce cas, l'infrastructure n'est pas envisagée dans sa dimension relationnelle.

L'objectif ici n'est pas de blâmer le projet mais de montrer que l'infrastructure bâtie au cours du temps constitue un tout et que des innovations ou des changements radicaux peuvent avoir des impacts importants, notamment sur des services tiers et des usagers. 

Un autre exemple est celui [des archives départementales de la Creuse](https://archives.creuse.fr/actualites/message-important-au-sujet-de-nos-permaliens-1). Elles ont dû effectuer une mise à jour de leurs permaliens en 2024. Cette opération est une opération de maintenance. Par le changement de nombreux permaliens, elle a eu un impact fort pour les usagers et nous pouvons saluer l'effort de communication réalisée par les AD, par anticipation sur cette modification aux conséquences potentiellement lourdes. 

C'est le sens de notre propos : la maintenance entraîne des actions régulières sur l'infrastructure et elle doit être évalué dans l'ensemble de ses inter-dépendances. L'un des moyens de maintenir un lien avec les usagers, notamment, c'est par la communication, comme dans l'exemple de la Creuse ou comme le fait la BNF sur sa [politique d'identifiants pérennes](https://www.bnf.fr/fr/politique-identifiants-bnf).

### Slide 3-4 - Exemple du cas américain

Sujet d'actualité qui nous vient des États-Unis et qui va nous permettre d'ouvrir une nouvelle notion, et peut-être permettre le débat ensuite. Suite à l'élection de Donald Trump un certain nombre de sujets et mots ont été décrétés comme étant à supprimer de la communication du gouvernement. Ceci a amené l'Armée américaine à [supprimer](https://mamot.fr/@Pyb/114122462441319003) plusieurs dizaines de milliers de fichiers images de sa photothèque en ligne. 

L'administration américaine avait depuis longtemps une politique d'ouverture et de réutilisation de ses contenus très forte. Les médias de cette plateforme sont donc très utilisés dans des contextes variés. Vincent Privat, Wikimédien, a ainsi collecté plus de 30.000 images de cette base afin de les déposer sur WikiCommons (bibliothèque média de l'environnement wiki). Le but était de rendre disponible des images pouvant ensuite servir d'illustration dans Wikipédia. Ce travail peu visible de la plupart des internautes à l'époque où il a été réalisé prend aujourd'hui une nouvelle dimension. En effet, il permet aujourd'hui qu'une partie des fichiers supprimés sur la plateforme de l'US Army soient toujours présents et accessibles à toutes et tous. 

La notion d'infrastructure et de maintenance prend ici tout leur sens, une infrastructure devient défaillante mais une autre prend en quelque sorte le relais, non pas dans une logique de réparation au moment de la cassure de service mais en amont, par anticipation. C'est l'attention portée par cette personne, mais aussi la philosophie des Communs numériques de la connaissance comme les projets Wikimedia, qui permettent de maintenir l'accès à l'information.

## Conclusion

Pour conclure, nous espérons, tout d'abord, vous avoir convaincu de l'intérêt d'envisager les archives numériques comme une infrastructure. Notre objectif était également, par les différents exemples précédents, avoir démontré qu'elle est non seulement un objet technique, mais aussi juridique (avec l'exemple australien), politique (avec l'exemple américain) et organisationnel (avec Sherpa). À travers ces exemples nous avons aussi montré l'importance pour les archivistes de prendre en compte la maintenance, et surtout d'envisager celle-ci en collaboration et en dialogue avec les usagers. 

Notre propos constitue une introduction au sujet et nous avons dû faire de nombreux choix pour tenir le temps imparti. Pour poursuivre nos réflexions, nous pourrions insister sur le rôle de la maintenance dans la préservation numérique et la pérennisation de l'information. Ou nous concentrer sur les multiples dépendances (éditeurs,) qui existent pour les archives numériques et les impacts que cela peut avoir sur la maintenance.
